baseURL = "https://github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Blog của Phạm Đức Tùng"
theme = "dream"
themesDir = "themes"   #Don't use this, only for netlify
publishDir = "docs"

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

googleAnalytics = ""

disqusShortname = "PDT_Geo"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	author = "Phạm Đức Tùng"
	description = "Just a random blog for GIS, Map and GEO."
	avatar = "https://raw.githubusercontent.com/UtkarshVerma/blog/source/static/images/myavatar.jpg"
	motto = "Just a random blog for GIS, Map and GEO"
	enableToc = true
	enableShareCard = true

	favicon = "/img/defaultFav.ico"

  	#Background settings
	enableColorBG= true

	#Post-displaying Settings
	enableTags = true
	enableCategories = true

	customCSS = ["https://cdn.rawgit.com/UtkarshVerma/hugo-dream-plus/ae11561d/exampleSite/static/css/highlight.css"]

	#Cards or posts shown per page
	itemsPerPage = 4

	#Set whether you're hosting "cards" or "post"
	contentType = "posts"

	#Enable Twitter Emoji
	twitterEmoji=true

[social]
	email = "doibay@pm.me"
	github = "doibay"
	stackoverflow = " "
	medium = "doibay_"
	twitter = "doibay_"
	siteStartYear = 2018